### ISSUE TITLE
HDMI and VGA ports not working

### ISSUE THREAD

**Issue by h1royuki** [the-braveknight/Lenovo-Z50-DSDT-Patch#10]
After commit ddf675e2639ad3dce702f0fdf8bc80db105b19a6 HDMI (no any reaction to connect cable) and VGA (macOS crashed) ports not working. Check it plz.

[IORegistry](http://rikka.io/yuly.zip)

**Comment by the-braveknight** [comment]
VGA is already not supported, HDMI should work well though.
Not enough data to look into, please ready my guide and post "Problem Reporting" files there.

**Comment by h1royuki** [comment]
Hmm, VGA working for me.

[SSDT](https://rikka.io/SSDT.zip)

➜  ~ kextstat|grep -y acpiplat
`   13    2 0xffffff7f8325d000 0x66000    0x66000    com.apple.driver.AppleACPIPlatform (5.0) 65E05472-6AE7-3308-8CC8-FA6CB0DB2AEE <12 11 7 6 5 4 3 1>`

➜  ~ kextstat|grep -y applelpc
 ` 107    0 0xffffff7f82d4a000 0x3000     0x3000     com.apple.driver.AppleLPC (3.1) F51595F0-F9B1-3B85-A1C3-F984DAD4107E <101 12 5 4 3>`

➜  ~ kextstat|grep -y applehda
`  100    1 0xffffff7f812d7000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (279.48) ED51F180-19C8-3DE1-AF81-0E389D98ADDE <99 98 74 12 7 6 5 4 3 1>`

`  119    0 0xffffff7f81479000 0xb5000    0xb5000    com.apple.driver.AppleHDA (9279.48) 806B8C17-50CA-3C6B-90B3-195F38D8FB89 <118 100 99 98 78 74 6 5 4 3 1>`

`  122    0 0xffffff7f83199000 0x2000     0x2000     com.apple.driver.AppleHDAHardwareConfigDriver (279.48) 14690424-1048-3F1D-8A3D-41657C97EB67 <4 3>`

**Comment by h1royuki** [comment]
➜  ~ sudo touch /System/Library/Extensions && sudo kextcache -u /
```
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext USBInjectAll.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext RealtekRTL8111.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakeSMC.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID_Intel_HD_Graphics.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID_Broadcom_WiFi.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext FakePCIID.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext CodecCommander.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmPatchRAM2.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext BrcmFirmwareRepo.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2Keyboard.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2Controller.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ApplePS2SmartTouchPad.kext
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext AppleHDA_CX20751.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext AppleBacklightInjector.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext ACPIBatteryManager.kext
kext-dev-mode allowing invalid signature -67013 0xFFFFFFFFFFFEFA3B for kext AppleMobileDevice.kext
```

**Comment by the-braveknight** [comment]
Please post all the files mentioned in "Problem Reporting" there, to the guide thread.

**Comment by h1royuki** [comment]
Oh, forgot Clover.
[Clover](https://rikka.io/Clover.zip)

**Comment by the-braveknight** [comment]
Connect the HDMI cabe and capture IOReg, and use the forums/guide thread so others can look into this as well.

**Comment by h1royuki** [comment]
[HDMI](https://rikka.io/HDMI.zip)

**Comment by the-braveknight** [comment]
Your IOReg looks OK. But it doesn't seem like you've plugged in the HDMI cable... test in Windows to verify that your HDMI/Display is working.

**Comment by h1royuki** [comment]
I tested HDMI on two monitors. HDMI works on Windows/Linux and after remove commit ddf675e2639ad3dce702f0fdf8bc80db105b19a6.

**Comment by the-braveknight** [comment]
Post IOReg of a working situation (after removing that commit)...

**Comment by h1royuki** [comment]
[HDMI/VGA](https://rikka.io/HDMIVGA.zip)

**Comment by the-braveknight** [comment]
It's pretty strange that you have VGA working without correct frame buffer patches... Also the HDMI is at port @1 just like mine, but it happens to have a problem switching when port @2 is absent in your case... I should probably revert that commit then. Do you have a lag after login/wake?

**Comment by h1royuki** [comment]
No, no any lags after login/wake.

**Comment by the-braveknight** [comment]
Please use the forums and post full "Problem Reporting" files there in a case by scenario so @RehabMan can take a look. 

The guide thread here: https://www.tonymacx86.com/threads/guide-lenovo-z50-70-z40-70-using-clover-uefi-10-11.179520/

**Comment by h1royuki** [comment]
I need to write now on forum or this problem is solved?

**Comment by the-braveknight** [comment]
It's not really solved yet, we need you to post there so we can investigate this issue further.

**Comment by h1royuki** [comment]
Ok, i'll posted this on forum. Thanks for help!

**Comment by the-braveknight** [comment]
I disabled the patches that were added in commit ddf675e.

**Comment by h1royuki** [comment]
Problem is solved. @the-braveknight, thanks for help!
